/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as RawThumbnailTokenRouteImport } from './routes/raw.thumbnail.$token'
import { Route as RawSessionTokenRouteImport } from './routes/raw.session.$token'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppSettingsPaneRouteImport } from './routes/_app.settings.$pane'
import { Route as AppOrganizationSlugASlugRouteImport } from './routes/_app.$organizationSlug.a.$slug'
import { Route as RawAArtifactIdVersionIdSplatRouteImport } from './routes/raw.a.$artifactId.$versionId.$'
import { Route as AppOrganizationSlugASlugVersionRouteImport } from './routes/_app.$organizationSlug.a.$slug_.$version'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const RawThumbnailTokenRoute = RawThumbnailTokenRouteImport.update({
  id: '/raw/thumbnail/$token',
  path: '/raw/thumbnail/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RawSessionTokenRoute = RawSessionTokenRouteImport.update({
  id: '/raw/session/$token',
  path: '/raw/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsPaneRoute = AppSettingsPaneRouteImport.update({
  id: '/settings/$pane',
  path: '/settings/$pane',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationSlugASlugRoute =
  AppOrganizationSlugASlugRouteImport.update({
    id: '/$organizationSlug/a/$slug',
    path: '/$organizationSlug/a/$slug',
    getParentRoute: () => AppRoute,
  } as any)
const RawAArtifactIdVersionIdSplatRoute =
  RawAArtifactIdVersionIdSplatRouteImport.update({
    id: '/raw/a/$artifactId/$versionId/$',
    path: '/raw/a/$artifactId/$versionId/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrganizationSlugASlugVersionRoute =
  AppOrganizationSlugASlugVersionRouteImport.update({
    id: '/$organizationSlug/a/$slug_/$version',
    path: '/$organizationSlug/a/$slug/$version',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AppHomeRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/settings/$pane': typeof AppSettingsPaneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/raw/session/$token': typeof RawSessionTokenRoute
  '/raw/thumbnail/$token': typeof RawThumbnailTokenRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/$organizationSlug/a/$slug': typeof AppOrganizationSlugASlugRoute
  '/$organizationSlug/a/$slug/$version': typeof AppOrganizationSlugASlugVersionRoute
  '/raw/a/$artifactId/$versionId/$': typeof RawAArtifactIdVersionIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AppHomeRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/settings/$pane': typeof AppSettingsPaneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/raw/session/$token': typeof RawSessionTokenRoute
  '/raw/thumbnail/$token': typeof RawThumbnailTokenRoute
  '/settings': typeof AppSettingsIndexRoute
  '/$organizationSlug/a/$slug': typeof AppOrganizationSlugASlugRoute
  '/$organizationSlug/a/$slug/$version': typeof AppOrganizationSlugASlugVersionRoute
  '/raw/a/$artifactId/$versionId/$': typeof RawAArtifactIdVersionIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/device': typeof DeviceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/home': typeof AppHomeRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/_app/settings/$pane': typeof AppSettingsPaneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/raw/session/$token': typeof RawSessionTokenRoute
  '/raw/thumbnail/$token': typeof RawThumbnailTokenRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/$organizationSlug/a/$slug': typeof AppOrganizationSlugASlugRoute
  '/_app/$organizationSlug/a/$slug_/$version': typeof AppOrganizationSlugASlugVersionRoute
  '/raw/a/$artifactId/$versionId/$': typeof RawAArtifactIdVersionIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/home'
    | '/invite/$invitationId'
    | '/settings/$pane'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/raw/session/$token'
    | '/raw/thumbnail/$token'
    | '/settings/'
    | '/$organizationSlug/a/$slug'
    | '/$organizationSlug/a/$slug/$version'
    | '/raw/a/$artifactId/$versionId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/home'
    | '/invite/$invitationId'
    | '/settings/$pane'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/raw/session/$token'
    | '/raw/thumbnail/$token'
    | '/settings'
    | '/$organizationSlug/a/$slug'
    | '/$organizationSlug/a/$slug/$version'
    | '/raw/a/$artifactId/$versionId/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/device'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/home'
    | '/invite/$invitationId'
    | '/_app/settings/$pane'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/raw/session/$token'
    | '/raw/thumbnail/$token'
    | '/_app/settings/'
    | '/_app/$organizationSlug/a/$slug'
    | '/_app/$organizationSlug/a/$slug_/$version'
    | '/raw/a/$artifactId/$versionId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  RawSessionTokenRoute: typeof RawSessionTokenRoute
  RawThumbnailTokenRoute: typeof RawThumbnailTokenRoute
  RawAArtifactIdVersionIdSplatRoute: typeof RawAArtifactIdVersionIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/raw/thumbnail/$token': {
      id: '/raw/thumbnail/$token'
      path: '/raw/thumbnail/$token'
      fullPath: '/raw/thumbnail/$token'
      preLoaderRoute: typeof RawThumbnailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/session/$token': {
      id: '/raw/session/$token'
      path: '/raw/session/$token'
      fullPath: '/raw/session/$token'
      preLoaderRoute: typeof RawSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/$pane': {
      id: '/_app/settings/$pane'
      path: '/settings/$pane'
      fullPath: '/settings/$pane'
      preLoaderRoute: typeof AppSettingsPaneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$organizationSlug/a/$slug': {
      id: '/_app/$organizationSlug/a/$slug'
      path: '/$organizationSlug/a/$slug'
      fullPath: '/$organizationSlug/a/$slug'
      preLoaderRoute: typeof AppOrganizationSlugASlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/raw/a/$artifactId/$versionId/$': {
      id: '/raw/a/$artifactId/$versionId/$'
      path: '/raw/a/$artifactId/$versionId/$'
      fullPath: '/raw/a/$artifactId/$versionId/$'
      preLoaderRoute: typeof RawAArtifactIdVersionIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$organizationSlug/a/$slug_/$version': {
      id: '/_app/$organizationSlug/a/$slug_/$version'
      path: '/$organizationSlug/a/$slug/$version'
      fullPath: '/$organizationSlug/a/$slug/$version'
      preLoaderRoute: typeof AppOrganizationSlugASlugVersionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppSettingsPaneRoute: typeof AppSettingsPaneRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppOrganizationSlugASlugRoute: typeof AppOrganizationSlugASlugRoute
  AppOrganizationSlugASlugVersionRoute: typeof AppOrganizationSlugASlugVersionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppSettingsPaneRoute: AppSettingsPaneRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppOrganizationSlugASlugRoute: AppOrganizationSlugASlugRoute,
  AppOrganizationSlugASlugVersionRoute: AppOrganizationSlugASlugVersionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DeviceRoute: DeviceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  RawSessionTokenRoute: RawSessionTokenRoute,
  RawThumbnailTokenRoute: RawThumbnailTokenRoute,
  RawAArtifactIdVersionIdSplatRoute: RawAArtifactIdVersionIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
